### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by cavalo-mORTO** [amarakon/dfm#5]
Hi, I've created an AUR package. You can check it here: https://aur.archlinux.org/packages/amarakonsdfm
I had to use a different name, as dfm was already taken. You can suggest another name if you to.
Would you kindly on your next release not include the git files so as to make the download faster?

**Comment by amarz45** [comment]
You can name it dmenu-dfm as many dmenu scripts follow that naming scheme.

> Would you kindly on your next release not include the git files so as to make the download faster?

Sure. I will include the program, the Makefile, the README and the license. I will also make the preview GIF in the README point to a URL rather than including the file in the repository. I will upload the next release for these reasons either today or tomorrow.

**Comment by amarz45** [comment]
Also, xdg-utils isn't a mandatory dependency. You could choose to install [sesame](https://github.com/green7ea/sesame) instead, which I recommend.

**Comment by cavalo-mORTO** [comment]
Guess I'll have to make an AUR package for sesame too.

**Comment by amarz45** [comment]
> I will upload the next release for these reasons either today or tomorrow.

I’m late on this but I’ll work on it.

**Comment by cavalo-mORTO** [comment]
If you want to include the AUR package in the installation section the url is https://aur.archlinux.org/packages/dmenu-dfm
